### PR TITLE
Add GCC target for building with the S130 SoftDevice

### PR DESCRIPTION
**Pull request by remay**
Minimal changes from bbc-microbit-classic-gcc to build with the S130v1 softdevice.
- replace S110 SD with S130 SD
- update linker script to reflect memory map
- update cmake definitions to (a) build with modified files (b) reduce heap allocation to 512 bytes

Would be fantastic is this could also be published to the yotta repository

### CODE REVIEW

**Comment by finneyj** [comment]
Hi @remay,

Thanks - yes, I think we should do that. Looks pretty good to me - just  one thing I noticed:

There's an updated version of the FOTA bootloader in use for the S110 target. The one you have here is limited to programming half the available memory range... can you pull the bootloader hex file out of the s110 target and see if that works for your s130 target ok? If so, update your target to us this? It would be good for us to be consistent here...

**Comment by remay** [comment]
Are you talking about `bootloader/BOOTLOADER_MICROBIT_noinit.hex`?  If so then my local diff shows no difference between the one in the current bbc-microbit-classic-gcc target and this new target.  I'll double check that my local copy is the latest, but I though it was last night when I was preparing this ...

**Comment by finneyj** [comment]
thanks @remay. It should show up as `BLE_BOOTLOADER_RESERVED.hex`

**Comment by finneyj** [comment]
oooh... looks like the github repo is out of sync with the yotta public registry. my bad. will fix.

**Comment by remay** [comment]
I've pulled BLE_BOOTLOADER_RESERVED.hex from the yotta repository - I'll leave you to update the bbc-microbit-classic-gcc target here.

**Comment by finneyj** [comment]
thanks @remay. I'll add this to the yotta registry shortly.

**Comment by finneyj** [comment]
yotta registry updated: bbc-microbit-classic-gcc-s130.

**Comment by remay** [comment]
Thank you

**Pull request merged**
